### ISSUE TITLE
Feature Request: Change Saturation

### ISSUE THREAD

**Issue by nxs-neo** [zb3/gnome-gamma-tool#26] opened 2024-12-03 20:57 UTC
Is there any way to increase or decrease saturation on gnome wayland?

**Comment by zb3** [comment] 2024-12-03 21:56
This cannot be acheved with 1D lut (we need to know all 3 color channels r, g, b) to adjust each and VCGT doesn't provide a way to do this.

Closing as duplicate of https://github.com/zb3/gnome-gamma-tool/issues/9

**Closed by zb3** 2024-12-03 21:56 UTC

**Comment by zb3** [comment] 2025-05-15 16:14
3 years late, but.. I've created a GNOME extension that can do this, however, it has some limitations:
https://github.com/zb3/gnome-saturation-extension

**Comment by nxs-neo** [comment] 2025-05-15 16:36
This is almost exactly what I was looking for. Just to slightly increase the saturation. Thank you
