### ISSUE TITLE
error after --delete

### ISSUE THREAD

**Issue by rubaboo** [zb3/gnome-gamma-tool#5] opened 2022-10-18 07:06 UTC
I used the `--delete` option, and now every call shows this. How to fix?

```
Current profile is /home/username/.local/share/icc/gnome-gamma-tool-5cf2d86e-60d7-4dc3-8b00-42493ccaf1c2
Traceback (most recent call last):
  File "/home/username/.local/share/src/gnome-gamma-tool/gnome-gamma-tool.py", line 350, in <module>
    main()
  File "/home/username/.local/share/src/gnome-gamma-tool/gnome-gamma-tool.py", line 315, in main
    profile_data = mgr.clone_profile_data(base_profile)
  File "/home/username/.local/share/src/gnome-gamma-tool/gnome-gamma-tool.py", line 239, in clone_profile_data
    return profile.load_icc(0)
gi.repository.GLib.GError: cd_icc_error: failed to load file: Error opening file /home/username/.local/share/icc/gnome-gamma-tool-5cf2d86e-60d7-4dc3-8b00-42493ccaf1c2: No such file or directory (0)
```

**Comment by rubaboo** [comment] 2022-10-18 07:09
I might have deleted that profile file myself, don't remember. Still, how do I get this wonderful script working again? Thank you!

**Comment by zb3** [comment] 2022-10-18 12:02
When you manually remove colord still reports that it's used even though the file doesn't exist. In this case ggt should default to sRGB.

However I'm not able to reproduce this error after using the `--remove` option alone. Could you please post the output (needs to include the missing filename) of ggt after using `--remove` but without manually deleting the file? 

After fixing this, I might think about creating some backup file so it could be restored, but I don't know when I'll have the time to implement it.

**Comment by zb3** [comment] 2022-10-18 12:05
To clarify the question... does the `--remove` option even change the gamma in your case? If it does, it means the colord reacts to file deletion.

**Comment by rubaboo** [comment] 2022-10-18 17:27
I did not play with gamma, only brightness. `--remove` does not change it back.

**Comment by BinaryGenius** [comment] 2022-10-18 22:53
Did I hear wayland this might be up your ally if extensions are okay with you. https://github.com/F-i-f/soft-brightness

**Comment by rubaboo** [comment] 2022-10-18 23:28
Not that I'm a pro or anything, but here's what I googled:

- There are two approaches for filtering blue light: the transparent overlay approach and the color transform approach. Color transform preserves contrast considerably better
- Soft Brightness uses an alpha overlay

I'm guessing using icc profile means "color transform approach"?

**Comment by BinaryGenius** [comment] 2022-10-18 23:48
I think soft brightness is the only promising approach and actually has a chance to be merged into native gnome a lot of features start off as extensions. The extension gives you a little bar under the volume that you can slide to change the brightness. The only reason I use this script is because I have an nvidia card and soft brightness has issues with xorg. If you can use wayland just fine soft brightness is a great choice.

**Comment by zb3** [comment] 2022-10-22 10:11
@rubaboo, since I can't reproduce this locally, could you please test whether the https://github.com/zb3/gnome-gamma-tool/tree/fix-remove branch works? It looks like in your case colord doesn't react to file deletion, so in that commit I first remove the profile via colord, then I delete the file. That should work, but I can't test it.

**Comment by zb3** [comment] 2022-11-27 15:47
Should be fixed by https://github.com/zb3/gnome-gamma-tool/commit/70114a9505182416e0c6c0d004eb9b11a1ccc8a7

**Closed** 2023-11-21 11:21 UTC
